# Generated by Django 5.2.5 on 2025-12-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_alumno_apoderado'),
        ('academico', '0003_auto_20241113_2305'),
    ]

    operations = [
    ]
